import { CashCollection, CollectionType } from "./cash-collection.model";
import { CashAllocation } from "./global.model";

export const CashCollections: CashCollection[] = [
    {
      id: 'cc_001',
      date: new Date('2024-12-05'),
      time: '09:30 AM',
      receivedFromId: 'mbr_123',
      receivedFromName: 'John Doe',
      cashAllocation: CashAllocation.onHand,
      collectionType: CollectionType.membershipFee,
      amount: 500,
      remarks: 'Membership fee for the year 2025',
      userId: 'user_001',
      userName: 'Admin User',
    },
    {
      id: 'cc_002',
      date: new Date('2024-12-05'),
      time: '10:15 AM',
      receivedFromId: 'mbr_456',
      receivedFromName: 'Jane Smith',
      cashAllocation: CashAllocation.inBank,
      collectionType: CollectionType.savings,
      amount: 2000,
      remarks: 'Monthly savings deposit',
      userId: 'user_002',
      userName: 'Cashier',
    },
    {
      id: 'cc_003',
      date: new Date('2024-12-05'),
      time: '11:00 AM',
      receivedFromId: 'loan_789', 
      receivedFromName: 'Alice Johnson',
      cashAllocation: CashAllocation.onHand,
      collectionType: CollectionType.loanReceivables,
      amount: 5000,
      remarks: 'Loan payment for Loan ID: loan_789',
      userId: 'user_001',
      userName: 'Admin User',
    },
    {
      id: 'cc_004',
      date: new Date('2024-12-05'),
      time: '02:45 PM',
      receivedFromName: 'Walk-in Client', // No receivedFromId for walk-in clients
      cashAllocation: CashAllocation.inBank,
      collectionType: CollectionType.others,
      amount: 1000,
      remarks: 'Donation for the cooperative',
      userId: 'user_002',
      userName: 'Cashier',
    },
    {
      id: 'cc_005',
      date: new Date('2024-12-05'),
      time: '03:30 PM',
      receivedFromId: 'mbr_987',
      receivedFromName: 'Bob Williams',
      cashAllocation: CashAllocation.onHand,
      collectionType: CollectionType.koopPaluwagan,
      amount: 1500,
      remarks: 'Koop Paluwagan deposit',
      userId: 'user_001',
      userName: 'Admin User',
    },
  ];