import { Collection } from "./collection.model";
import { DepositType } from "./deposit.model";
import { LoanType } from "./loan.model";

export const Collections: Collection[] = [
    {
      id: 'col_001',
      date: new Date('2024-12-08'),
      orNo: 'OR00123',
      memberId: 'mbr_123',
      memberName: 'John Doe',
      paymentType: DepositType.savings,
      amount: 2000,
      remarks: 'Monthly savings deposit',
      userId: 'user_001',
      userName: 'Admin User',
      approved: true,
    },
    {
      id: 'col_002',
      date: new Date('2024-12-08'),
      orNo: 'OR00456',
      memberId: 'mbr_456',
      memberName: 'Jane Smith',
      paymentType: LoanType.privilege,
      amount: 5000,
      remarks: 'Loan payment for Privilege Loan',
      userId: 'user_002',
      userName: 'Cashier',
      approved: true,
    },
    {
      id: 'col_003',
      date: new Date('2024-12-08'),
      orNo: 'OR00789',
      memberId: 'mbr_789',
      memberName: 'Alice Johnson',
      paymentType: DepositType.timeDeposit,
      amount: 10000,
      remarks: 'Time deposit placement',
      userId: 'user_001',
      userName: 'Admin User',
      approved: true,
    },
    {
      id: 'col_004',
      date: new Date('2024-12-08'),
      orNo: 'OR01011',
      memberId: 'mbr_101',
      memberName: 'Bob Williams',
      paymentType: LoanType.productive,
      amount: 3000,
      remarks: 'Loan payment for Productive Loan',
      userId: 'user_002',
      userName: 'Cashier',
      approved: true,
    },
    {
      id: 'col_005',
      date: new Date('2024-12-08'),
      orNo: 'OR01213',
      memberId: 'mbr_123',
      memberName: 'John Doe',
      paymentType: DepositType.koopPaluwagan,
      amount: 1500,
      remarks: 'Koop Paluwagan deposit',
      userId: 'user_001',
      userName: 'Admin User',
      approved: true,
    },
    {
      id: 'col_006',
      date: new Date('2024-12-08'),
      orNo: 'OR01415',
      memberId: 'mbr_456',
      memberName: 'Jane Smith',
      paymentType: DepositType.pensionSavings,
      amount: 5000,
      remarks: 'Pension savings contribution',
      userId: 'user_002',
      userName: 'Cashier',
      approved: true,
    },
    {
      id: 'col_007',
      date: new Date('2024-12-08'),
      orNo: 'OR01617',
      memberId: 'mbr_789',
      memberName: 'Alice Johnson',
      paymentType: LoanType.ebike,
      amount: 1000,
      remarks: 'E-bike loan payment',
      userId: 'user_001',
      userName: 'Admin User',
      approved: true,
    },
    {
      id: 'col_008',
      date: new Date('2024-12-08'),
      orNo: 'OR01819',
      memberId: 'mbr_101',
      memberName: 'Bob Williams',
      paymentType: DepositType.shares,
      amount: 20000,
      remarks: 'Shares deposit',
      userId: 'user_002',
      userName: 'Cashier',
      approved: true,
    },
    {
      id: 'col_009',
      date: new Date('2024-12-08'),
      orNo: 'OR02021',
      memberId: 'mbr_123',
      memberName: 'John Doe',
      paymentType: DepositType.mutualBenefits,
      amount: 1000,
      remarks: 'Mutual benefits fund contribution',
      userId: 'user_001',
      userName: 'Admin User',
      approved: true,
    },
    {
      id: 'col_010',
      date: new Date('2024-12-08'),
      orNo: 'OR02223',
      memberId: 'mbr_456',
      memberName: 'Jane Smith',
      paymentType: DepositType.others,
      amount: 500,
      remarks: 'Miscellaneous payment',
      userId: 'user_002',
      userName: 'Cashier',
      approved: true,
    },
  ];