import { MemberExtended, MemberGenerator } from "./member.model";

export const sampleMembers: MemberExtended[] = [
    {
      id: 'mbr_001',
      lastname: 'Doe',
      firstname: 'John',
      middlename: 'A',
      address1: '123 Main St',
      barangay: 'Barangay 1',
      municipality: 'Makati',
      province: 'Metro Manila',
      gender: 'Male',
      birthday: new Date('1990-05-15'),
      contactNo: '1234567890',
      email: 'john.doe@example.com',
      facebook: 'fb.com/johndoe',
      occupation: 'Software Engineer',
      business: 'Acme Corp',
      tinNo: '123-456-789',
      membershipDate: new Date('2023-08-20'),
      lastTransaction: new Date('2024-10-26'),
    },
    {
      id: 'mbr_002',
      lastname: 'Smith',
      firstname: 'Jane',
      middlename: 'B',
      address1: '456 Elm St',
      barangay: 'Barangay 2',
      municipality: 'Quezon City',
      province: 'Metro Manila',
      gender: 'Female',
      birthday: new Date('1985-11-22'),
      contactNo: '9876543210',
      email: 'jane.smith@example.com',
      facebook: 'fb.com/janesmith',
      occupation: 'Data Analyst',
      business: 'Beta Inc',
      tinNo: '987-654-321',
      membershipDate: new Date('2024-01-15'),
      lastTransaction: new Date('2024-11-15'),
    },
    {
      id: 'mbr_003',
      lastname: 'Johnson',
      firstname: 'Alice',
      middlename: 'C',
      address1: '789 Oak St',
      barangay: 'Barangay 3',
      municipality: 'Manila',
      province: 'Metro Manila',
      gender: 'Female',
      birthday: new Date('1992-03-08'),
      contactNo: '5555555555',
      email: 'alice.johnson@example.com',
      facebook: 'fb.com/alicejohnson',
      occupation: 'Teacher',
      business: 'Gamma School',
      tinNo: '555-555-555',
      membershipDate: new Date('2023-05-10'),
      lastTransaction: new Date('2024-09-02'),
    },
    {
      id: 'mbr_004',
      lastname: 'Williams',
      firstname: 'Bob',
      middlename: 'D',
      address1: '101 Pine St',
      barangay: 'Barangay 4',
      municipality: 'Pasig',
      province: 'Metro Manila',
      gender: 'Male',
      birthday: new Date('1978-09-12'),
      contactNo: '1111111111',
      email: 'bob.williams@example.com',
      facebook: 'fb.com/bobwilliams',
      occupation: 'Doctor',
      business: 'Delta Hospital',
      tinNo: '111-111-111',
      membershipDate: new Date('2024-03-28'),
      lastTransaction: new Date('2024-11-20'),
    },
    {
      id: 'mbr_005',
      lastname: 'Brown',
      firstname: 'Charlie',
      middlename: 'E',
      address1: '202 Cedar St',
      barangay: 'Barangay 5',
      municipality: 'Mandaluyong',
      province: 'Metro Manila',
      gender: 'Male',
      birthday: new Date('1982-06-01'),
      contactNo: '2222222222',
      email: 'charlie.brown@example.com',
      facebook: 'fb.com/charliebrown',
      occupation: 'Artist',
      business: 'Epsilon Gallery',
      tinNo: '222-222-222',
      membershipDate: new Date('2023-11-05'),
      lastTransaction: new Date('2024-07-18'),
    },
  ];

  export const transformedMembers = sampleMembers.map(member => {
    const memberGenerator = new MemberGenerator(member);
    return {
      ...member,
      name: memberGenerator.getFirstAndLastname(),
      age: memberGenerator.getAge(),
      isActive: memberGenerator.getIsActive(),
      address: memberGenerator.getAddress(),
    };
  });